#!/bin/sh

set -e

cd /opt/ld/ai-configs-intro/terraform/challenge-01
echo "project_key = \"${LD_PROJECT_KEY}\"" > terraform.tfvars
terraform init -input=false

cd /opt/ld/ai-configs-intro/terraform/challenge-05
echo "project_key = \"${LD_PROJECT_KEY}\"" > terraform.tfvars
terraform init -input=false

exit 0
