#!/bin/sh

set -e

cd /opt/ld/ai-configs-intro/terraform/challenge-01
terraform apply -auto-approve

python3 /opt/ld/ai-configs-intro/terraform/challenge-01/patch-server.py
service togglewear restart

cd /opt/ld/ai-configs-intro/terraform/challenge-05
terraform apply -auto-approve

exit 0
